name: Server Setup with Docker
on:
  workflow_dispatch:

jobs:
  setup-code:
    name: Install with Docker on Ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 1000

    steps:
      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Configure Firewall
        run: |
          sudo ufw allow 54321/tcp
          sudo ufw allow 443/tcp
          sudo ufw allow 80/tcp
          sudo ufw reload

      - name: Pull Docker Image
        run: |
          docker pull alireza7/x-ui:latest

      - name: Run Container
        run: |
          docker run -d \
            --name x-ui \
            -p 54321:54321 \
            -p 443:443 \
            -p 80:80 \
            -e XRAY_VMESS_AEAD_FORCED=false \
            -v $PWD/db/:/etc/x-ui/ \
            -v $PWD/cert/:/root/cert/ \
            alireza7/x-ui:latest

      - name: Wait for Service to be Ready
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:54321 > /dev/null; then
              echo "x-ui is up and running!"
              exit 0
            else
              echo "Waiting for x-ui to start..."
              sleep 5
            fi
          done
          echo "x-ui did not start in time."
          exit 1

      - name: Verify Installation
        run: |
          docker ps -a | grep x-ui
          curl -s http://localhost:54321

      - name: Print Access Info
        run: |
          echo "Panel Access:"
          echo "http://$(curl -s ifconfig.me):54321"

      - name: Keep Alive
        run: |
          sudo apt-get install -y python3

          cat > loop.py <<'EOF'
          import time

          start = time.time() + 1000

          while True:
              if start <= time.time():
                  break
              print("Running...")
              time.sleep(13)
          EOF
          python3 loop.py
