name: Docker Setup
on:
  workflow_dispatch:

jobs:
  docker-setup:
    name: Deploy with Docker
    runs-on: ubuntu-latest
    timeout-minutes: 1000

    steps:
      - name: Prepare Workspace
        run: |
          mkdir -p x-ui/{db,cert} && cd x-ui
          echo "Working directory: $PWD"

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl enable --now docker
          sudo usermod -aG docker $USER

      - name: Configure Firewall
        run: |
          sudo ufw allow 54321/tcp
          sudo ufw allow 443/tcp
          sudo ufw allow 80/tcp
          sudo ufw --force enable
          sudo ufw reload

      - name: Run Container
        run: |
          cd x-ui
          docker run -itd \
              -p 54321:54321 -p 443:443 -p 80:80 \
              -e XRAY_VMESS_AEAD_FORCED=false \
              -v $PWD/db/:/etc/x-ui/ \
              -v $PWD/cert/:/root/cert/ \
              --name x-ui --restart=unless-stopped \
              alireza7/x-ui:latest

      - name: Verify Container Status
        run: |
          docker ps -a | grep x-ui
          docker logs x-ui --tail 50

      - name: Check Service Readiness
        run: |
          for i in {1..10}; do
            if docker exec x-ui curl -s http://localhost:54321; then
              echo "X-UI is ready!"
              exit 0
            fi
            echo "Waiting for X-UI to start... ($i/10)"
            sleep 10
          done
          echo "X-UI failed to start!"
          exit 1

      - name: Display Access Info
        run: |
          PUBLIC_IP=$(curl -s ifconfig.me)
          echo "=============================================="
          echo "X-UI Panel Access: http://$PUBLIC_IP:54321"
          echo "Default Credentials: admin/admin"
          echo "=============================================="
